### ISSUE TITLE
Яндекс Погода

### ISSUE THREAD

**Issue by kesnfs** [hant0508/uBlock-fillters#2]
С вашими фильтрами не показывается список предложений в поиске городов в яндекс.погоде
Скрин, о том что имею в виду
https://pp.vk.me/c837338/v837338073/1b6a1/OLw0KLJ6Vz8.jpg

**Comment by hant0508-zz** [comment]
Также не показывался и выпадающий список на главной странице Яндкса. Исправлено https://github.com/hant0508/uBlock-fillters/commit/74c3373f61d9c9ad994e5009eeef370899a99c89.
